FROM resin/rpi-raspbian:jessie

MAINTAINER ralf.zeidler@radio-tracking.eu

RUN apt-get update && \
    apt-get install -y apache2 apache2-doc apache2-utils mysql-server mysql-client sqlite3 \
					php5 php5-mysql  libapache2-mod-php5 php5 php-pear php5-xcache php7-pdo_sqlite phpmyadmin
	

